#!/usr/bin/env bash

# docker-build: trigger a rebuild of the latest master/tag on docker hub

[[ -n "${DOCKERHUB_ENDPOINT}" ]] || \
  { echo "No endpoint?" >&2 ; exit 2; }

[[ "${TRAVIS_BRANCH}" == "master" ]] || \
  { echo "Refusing to trigger a rebuild on non-master" >&2 ; exit 1; }

curl -H "Content-Type: application/json" --data '{"build": true}' -X POST \
  "${DOCKERHUB_ENDPOINT}"
